### ISSUE TITLE
View_trends() tpl parsing issue pyfas 0.4.1

### ISSUE THREAD

**Issue by Christa-K** [gpagliuca/pyfas#28] opened 2023-02-17 09:42 UTC
Hi,

view_trends() sometimes parses the variable description wrong, causing issues with data extraction down the line.  These results are for the same .tpl file but VISL variable is presented correctly while VISG is not.

I am using pyfas 0.4.1 in a jupyter notebook.

Thank you!

**Comment by gpagliuca** [comment] 2023-02-17 10:13
Hi, thanks for sharing. Would be possible to have the full tpl or at least the section where the parsing fails?

**Comment by Christa-K** [comment] 2023-02-17 11:08
Hi Giuseppe, I thought you may ask this, but due to confidentiality issues I am afraid I can't share it. Could you try with one of your own tpls that has the troublesome variables in? I can tell you the issue is with specific variables: VISG, VISHL, CGR, WGR, VISWT, ID. All other variables are fine. I can't see any difference in how the variables are listed in the tpl file catalog compared to the ones that work, the separators are the same (single spaces and " ' " symbols), no missing CR and LF, no errant indents.

**Comment by gpagliuca** [comment] 2023-02-17 12:11
Most likely the parsing fails because of something present into the position name, without that it is quite difficult to fix.

Would be possible to share just a few lines of the variables catalogue (of course including the problematic ones) without any data?

Something like that:

> QG 'BOUNDARY:' 'BRANCH:' 'JUMPER' 'PIPE:' 'PIPE-5' 'NR:' '1'  '(M3/S)' 'Gas volume flow'
> QLT 'BOUNDARY:' 'BRANCH:' 'JUMPER' 'PIPE:' 'PIPE-5' 'NR:' '1'  '(M3/S)' 'Total liquid volume flow'
> QLTHL 'BOUNDARY:' 'BRANCH:' 'JUMPER' 'PIPE:' 'PIPE-5' 'NR:' '1'  '(M3/S)' 'Volumetric flow rate oil'
> QLTWT 'BOUNDARY:' 'BRANCH:' 'JUMPER' 'PIPE:' 'PIPE-5' 'NR:' '1'  '(M3/S)' 'Volumetric flow rate water'
> QGST 'BOUNDARY:' 'BRANCH:' 'JUMPER' 'PIPE:' 'PIPE-5' 'NR:' '1'  '(SM3/S)' 'Gas volume flow at standard conditions'
> QOST 'BOUNDARY:' 'BRANCH:' 'JUMPER' 'PIPE:' 'PIPE-5' 'NR:' '1'  '(SM3/S)' 'Oil volume flow at standard conditions'
> QWTST 'BOUNDARY:' 'BRANCH:' 'JUMPER' 'PIPE:' 'PIPE-5' 'NR:' '1'  '(SM3/S)' 'Total water (liquid and vapour) volume flow at standard conditions'

**Comment by Christa-K** [comment] 2023-02-17 14:47
Thank you for this. I am reluctant to share, I apologise. This is out of an abundance of caution. Yes I assume it's the regex, thank you for sharing the relevant bit, it would take me forever to find it. The problem is I don't see any difference in the text for these variables that would trip it up. My python is not great, let me look at the regex more carefully and edit this comment if I find anything. Again apologies for not sharing the tpl file.

**Comment by gpagliuca** [comment] 2023-02-17 20:52
The only potential source of confidential info here is the position names. 
Now that you understand the problem can you create some dummy variables with different position names that would me the possibility to reproduce the issue?

**Comment by Christa-K** [comment] 2023-02-17 21:49
Yes, please find attached a sample of that .tpl file, where the variables are listed. 

The case is exactly the same I just changed the position names. I get the same issue for the same variables (VISG, VISHL, CGR, WGR, VISWT, ID). I realise now that all the descriptions that have issues have special characters of some kind in them (=, commas, slashes, brackets) that the other variables don't have. But these symbols are included in the regex above so should theoretically be included?

[tpl_file_excerpt.txt](https://github.com/gpagliuca/pyfas/files/10771855/tpl_file_excerpt.txt)

**Comment by gpagliuca** [comment] 2023-02-18 14:32
Sorry but I was not able to reproduce the issue: all the tested variables below worked just fine:

```
In [1]: import re
In [2]: st0 = "ROWT 'POSITION:' 'D/S VALVE 2' '(KG/M3)' 'Water density'"
In [3]: st1 = "ID 'POSITION:' 'HEADER 2 INLET' '(-)' 'Flow regime: 1=Stratified, 2=Annular, 3=Slug, 4=Bubble.'"
In [4]: re.findall("\'[\w\(\) \= \, \. \-\:\/]+\'", st0)
Out[4]: ["'POSITION:'", "'D/S VALVE 2'", "'(KG/M3)'", "'Water density'"]
In [5]: re.findall("\'[\w\(\) \= \, \. \-\:\/]+\'", st1)
Out[5]: 
["'POSITION:'",
 "'HEADER 2 INLET'",
 "'(-)'",
 "'Flow regime: 1=Stratified, 2=Annular, 3=Slug, 4=Bubble.'"]

In [6]: st2 = "VISG 'POSITION:' 'HEADER 2 INLET' '(N-S/M2)' 'Effective gas viscosity including mud and non-Newtonian effects  = shear stress divided by shear rate of Newtonian fluid flow in 
   ...: pipe'"
In [7]: re.findall("\'[\w\(\) \= \, \. \-\:\/]+\'", st2)
Out[7]: 
["'POSITION:'",
 "'HEADER 2 INLET'",
 "'(N-S/M2)'",
 "'Effective gas viscosity including mud and non-Newtonian effects  = shear stress divided by shear rate of Newtonian fluid flow in pipe'"]
```

**Comment by XT3V3** [comment] 2023-03-22 09:39
@Christa-K  tpl.py was updated a year ago. The problems you mentioned should've been fixed. Are you using the latest version of the tpl.py file? If you installed Pyfas by using "pip install" you probably ended up with an older version of this file. Perhaps you try to download the tpl.py file directly from Github and replace it with existing file on your computer?

**Comment by XT3V3** [comment] 2023-03-25 09:41
@gpagliuca Perhaps we should update Pyfas to version 0.4.2 to make sure all the updated files get installed? Then we can close this thread.

**Comment by gpagliuca** [comment] 2023-03-25 21:21
good point, let me do that

**Closed** 2023-03-25 21:53 UTC
